# 触发条件
name: 'Github Action Weather Reporter'

on: 
  push: 
  schedule: 
   - cron: '0 21 * * *'
   
# 运行流程
runs-on: ubuntu-latest
steps: 
  - name: 'Checkout codes'
    uses: actions/checkout@v1
    
  - name: 'Get weather report'
    run: bash ./weather.sh
    
  - name: 'Send mail'
    uses: dawidd6/action-send-mail@master
    with:
      serveraddress: smtp.163.com
      serverport: 465
      username: ${{ secrets.MAILUSERNAME }}
      password: ${{ secrets.MAILPASSWORD }}
      subject: Shanghai Weather Report
      body: file://result.html
      to: yifeng.ruan@gamil.com
      from: GitHub Actions
      content_type: text/html
